travis:
  secure:
    BINSTAR_TOKEN: nM0a7zrdbEbbV9c0airXrC1/Rfg0Q2KqtL6A5AS9OdVPEZIHgRIxYjL3DQp/JYJyHYkQFKQQ6tjhYiaYksGyGHOZGoEtJI4jkiXZc+deJRJlNzR0V+imEXaxbKbGK+FF6hl58xcuFstixUSSJh8eoRKp+Ed4J73wSS+rUjyC6ghpUKSF5Ww/etTFOqXiAEu8GbhkHFPWjmUOPotm5//7NQxc3Q3Hipp+4Mc9pV8tlioR4QvEWf/8qu1GUk31HPH8XvhF9QIF075mRUuqukWRP2+eMVOqM4W/6VTNoRxvUcGtob3HgyckWW4bu6IyIFDrHZ6GKPrZ81CjUvOT9VVOlf8QIMYo6BfqJxwupRAJ86ZLTRY9DwqAdal5BwYkVE/XStjf2semHoNcVKTvSWZiv8MjHsas0rdZZcbrTaaN933ym5CjQ2CAyG60djuteHiNl3vpmFFbI6j7IgJ2gAyftelOvopzSeTQK2WphKv22zSpyZYzaBc6PUunmN3XMNlQc/AJIsFGZHoFCvxobRp+Og68n6FbqgUZdWNRlpLVHPN2ynjP2MJD+g2mmjINnovn38CYyCxzG925H/tEOA+tIDfDKQYVbCcxJmAAVstFelsGdiKlEogBYglx8GG3eTlXB8/06sEH85VR7mGECH5NKtQiaXqyBMORr+58yMyz2vI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
