travis:
  secure:
    BINSTAR_TOKEN: eWLDLAwt9tcr/lG2uJOIq8OJW+gW2RA+B+cTmGILQI1eHLzvZVYIsJ7nQZTwFAmatHKKGPZAOii3bCsxV7La3nupx8xuYq35wTykU26Qb4i/IMM9Vn18RCTRnpx/6grCcXinTFLWb7UBwtQCmzeO5IWXMiuM3dUQ9H+ImQb16eLCpbnU2GPfDAy/bvhyIgZQjxnCCyCl1hSSbp9EE2n9UOksVolmpO+pye03Jikmcs9gx46JR08h3OqYuekhK9lUIebpZJknNl3B7B6CP99NmbiDZHrQcwmCyI2oNREhoDki65Jc88be/WAdpzwHzty5BrwJ8I1Pwx+sFK8GAspUv6YGxAwJUUCAPqiKffWAflE2HG7T+x5YuGgizPHLx6en7YH49Y0Ins9/QdMob3+G3C8l5ezQct5pDFhJ1HoLt4WT1AnTFGNEzbRrn64L9OaDf3E5IXzgjDsysWQtscAjbZ1vl3mQWolDuqW41MIr/r32oACYrtoV0ZtyexZTnazeZj7+lahNHtQ6s1kjjJXazRzdCmmHhIHe6BmlF0aysyWBJEa6Nunfv2XIj366HHvs7kX1bNz368PBgflij1HUQ0oiKebwvEmTm/gmIXaOGuDNb2ElKAMAkIePOpSgfNzOz1MSjnl+7NK1cX7CmRURTVK2tcvdwCHcF+dvzUKAZG0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
