travis:
  secure:
    BINSTAR_TOKEN: MqUEvmgXcLMVLMF8YJvqPtbRKAzYfcd5fgVXuplghzzvQCZ2eapymu4bbPWiEDB2F3GK83RKe3WeJ9IPQt/O7jWoxQoewRhbjMH8f7lmW+7NXuI0dhxbFDbpPiGBhR9f9RiIAJOJjmT0IUnwv9y6dTSHFSRvaciUeDtdwtgyLjWmcsuC8W7C6h9SvEdPv6GgCLX4IQ9DvH7o5V4w0Me0wRUuvsVTOUiAAAqc1lW5V8EQweex42DbHcWEzMu3g+BKH1TzJ5rwIdJsNaKMUqGZYGA0u89qfP2olpMZAfXnpE5DiYevrKl5wk+w+kqUiiFTHG3DMReKab2C4JT79tEeWw38f4MKIM3d4rUdLdOgWI9M+GMSDlGdlr46XQkqVW7UaJvVHBEiMINLA7QYR6OyPmViW8vucIiWiTz1ucXS8IvVsVmyiqIgYu70KeKgpSuTYflOT4Wy2wFhY0LcdPvuFGxr7xzLGQEwCYl4dakI5RNI96E2/0SJy3t1YQPeDq7K/oldZXzVqBGJ5MBtQlyr5P2+b3KPzVmGQbCO2K7jAWTRwuk5UkHn0r+jDDxuOB0vNP/sSjjLXhgmkxIsDS04P5da96GbZQeZMCEipMzMHPQupcsi3t6m4BYXslky5wKyF4FnRy3N8QIiNRFUsO/SN2gVWX+f2PfOsUIYYW5IfVU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
