travis:
  secure:
    BINSTAR_TOKEN: Ct5gv0UWdeE8sbVAWDNc3kdRs5ay3tCd0WQMcaBrDVQAwBdqx+c+W7KonoF66/WLIgLeBxCg+WjhfPWHCbAPhqnMWt/F/mQGoGtO/FMJInYSZr1VstUh9B3DGugPUbR9qYrMVzUacAFfHEgM5l2c6O3GojLQj43mHn/YtBNRQAv8FDtxO35knT8Rl9dCWriyFi9AJxF/QPBJ3ECqNcB19ESCbYTW3/g020Kk3vpOXof0lnB92/UkOOLDySUb/I/fUmijTOyWZwaoZ4Ok908b3bvVHcDiDQkKnzY/keKfB9in1AxuoOjGXo4O9UHcJgx7HiGLxaf+8OI4iZgGKKIG297NNVpMTuPPAzBFI14woOp+fOnfMRsXK1Gxrw4jhHnkE32fRbCm49IFRzNglgoL70Ip9X0kwTJ8wmwJPfHdcMyJpUL5HGAEsOhqaP4jGEqNJUnJEsNaCeRY3+gOuvTgHdno+2H42q2eL1I37GVGqYcgMYWrdrtqxJvVSXJQVyfsjmKfCu7r1/5HcRAYF1MKulW7W7WyrnTwW5rCKmnmBUaBOVmoTmVCe86CwxTQhhI6ofdXEmTJZcCO3ebyDVUDytZUadXXlL4ozpYtVgBU2QRM43Zbkv8OOjo8Cv2vhafZEn3Wd9F07kg4cRF/uQGCzStP7t/ESxIbdGVWb8zdyc8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
