travis:
  secure:
    BINSTAR_TOKEN: nCcBr0np3MmIuJPwu+owdlEoemXeDqQUCmS36fhkZe5WnzHQ2BnyEYwJkVksfAVLhYK6bguChCiv9zSOVedB+BdTi2dhv8J8SMaTSYyj/ndSTS/AlejMlOCmRW//9k1fQHjcBl3O2tpZ53ziOg7hy7UV7Zq6LsovKpTIBb/fXixzAj5Z/hs2p0PE70Tgd4LSxyiaqQDBpxv6gh5rmMcMyOy4oGfY03E7k48H1qkNMucmzNKKncgA+lPBj6QDeO4GKq3f8P9Zofq+bcRmKAv1dRRH/07swhRJ5ByXAZsID+sRw68IIbfXUktFUoHSzck190qB9GGW6GPhyFcXxEWab7yEaj8UcWck3btycaJx/WRmDK+oCKBgTFhMgSi5EicA57BjEwrwdLT2x13B9OwcSk/cnxj0tSUGq3KwSF0WJABZkq/h7AABLaNGDJUiY6WDJto4C79UE8OyTbsSmAzOkzgtFi7qHPV8BBOJ7WB22ZdFmiHzOsMzHXNpxp+mt/hhvFPYC+n8dHcCfzYbf5Ed9q7TxfsG7ikz46vpdQ4X/zWJ11UXJLcBhXE0T+UPJqCE+nC9/vDFZgqDNH0EDsJienByprYVTtRgeexDvUq0t+wJO/f4gTn4ZipMeS1IEJ62TF8kvB2mkKDbB+EGqFv3UH9PYj0gLpUNrIMNJmHVrPY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
