travis:
  secure:
    BINSTAR_TOKEN: ji0j0kTARhv1YT0GVjJfPqVyft8H+fKMnX+TMEsTRX9tFnyIeKRq1kca3M54WFZV1BDovuSR0cuDPKHsxIA7A4rcO3AqXkHn94M9spWdkA09OgY0EDAYglfB/ohTfniqPD21hULlnooKBCJul9SVuS556Q1d9uFd503UTobkmZGP+3PhPfdQkA6x3QEAd8J+5WtT/u87FqsCYOwQpfhiwjtzuwY1tdqlBfy4Aea+9xk3WrDXX1gauSy4jCN8aR9sfTnAXp9SArLrKrMcboVvyaJbI0xEGl2te75ASm1s3Ng+YkZtAmMi9rz8BF+5EtlFBx2EhGV1JHzxUjBZ1MybkMMcRvIvgl/A3apUpU5pkDrvn99CPySzQA/RN/FeITKl+tFw4CUWBQrlSmbp8BPiw1pxTRkUSqT/fk3DWa573nvAAouKX78epTSJ9ZiUfz85wRlyxlAgFivfGnACUYDQATCYDz35f7BL6RNBDevhZOUd6LVYISFZqOUL4zhEkcedFYHGYjLcexFOLr4VtFfCPuWCi2KQfHfq/Vw3Rs4jpdiKbAN85BxIPGKYrnhIjOr2ACn9Z/GORhPMYHxXB7Xn9MT2biQw5Wxyqw1YV2ELxu/kCfPq3uAlXMkgqOU+SRXJY1iSKbqpIySQSVtEtdiaMGDVAmx4QBemJA46vAVyBNE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
