travis:
  secure:
    BINSTAR_TOKEN: Kdj6JmSyfGIebdrFn8TCH52kj7ZkrkpYHE1DuZMNGXWkqwJIk6okWHdJl44GXcEW92DhpHQLtRLCaedHpGKo8H/Qe67OmkqfKaM7kHJrehelbdhvcSzmKJZjC1/m7HjMgLxsprEBUJBXinUq9JertDN04PzaUHAEPnQh4cf7+O2Wf42TcIFwcuEQYc4YNik9QWdjNGAFQQT+qJsFx6CyqhJu2qBJ0J2HHNDo1rwaETKKQOIWp4kqb5aBCYXkniLcIVWcRt82mVEejVae+w0ftZpOz4WES1u1cK8wDkgU3baM+dIH6TC43i0rn+UoVPgPp+AxVlmel86IhiNqpxMgII5pE+oqG46VXzPNKH7pdquPWm7rg6XSRBk0gTPm7f/6tiLzZyukz1g0i+I+75gKpV2olR3QN8KQ7d0EH94B6YnFcvEDYq6yIbI+Ib6iISgXASrdhoDJdC52cg9xUc3B6znUE2SY6143COtZ6W9UWSLXys3A2jP9yE25MOxNunRstYc0ik7hEG9tvx6910NYG0YZrKvjH3nHTauheg4V9Ai3Ijlh5c8cxCz0c/uNlk5fH1jc+9euyLK/jvvSNjQ1hYqyktVmsSA1Guqzz4GnTLv0mBJU9sjwnLm7CFwWi7RDQH2/1/CCP+ZdNeTQxwl8Tqaqb42OVQSFcchZ4hM2cic=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
